### ISSUE TITLE
タスク一覧

### ISSUE THREAD

**Issue by takamasa-suzuki001** [SuzukiTakamasa/LINEBot#1]
- [ ] .envファイルを利用するためにdotenvをimportする
`from dotenv import load_dotenv`

- [ ] 以下の定義のcsvを作成する

"No.","name","generation","type1","type2","hp","attack","defense","sp-attack","sp-defense","speed","trait1","trait2","dream-trait"

- [ ] 可能であればpolarsでデータ操作、抽出を行う

- [ ] 返すメッセージ自体は`TextSendMessage(text={RESPONSE})`で定義する

**Comment by SuzukiTakamasa** [comment]
完了
